@extends('layouts.app')

@section('content')
<div class="container-fluid py-3 overflow-auto">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card border-dark fixed-width">
                <div class="card-header bg-yellow text-center">
                    <h3>Klasyfikacja Generalna: Rajdowy Puchar Śląska 2017</h3>
                </div>
                <div class="card-body">
                    <div class="row justify-content-between align-items-center flex-wrap">
                        <h6 class="m-0 col text-left">
                            LP
                        </h6>
                        <h6 class="m-0 col-2 text-left">
                            Imię i nazwisko
                        </h6>
                        <h6 class="m-0 col-2 text-left">
                            Klasa
                        </h6>
                        <div class="m-0 col-5 d-flex justify-content-start">
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 1</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 2</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 3</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 4</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 5</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 6</small>
                            </h6>
                        </div>
                        <h6 class="m-0 col text-right">
                            PKT
                        </h6>
                        <h6 class="m-0 col text-right">
                            Miejsce
                        </h6>
                        <hr class="col-12 p-0">
                    </div>
                    <div class="lista"> 
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">1</h6><h6 class="m-0 col-2 text-left">F.Wójcik Mirski</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">56</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">2</h6><h6 class="m-0 col-2 text-left">P.Troszok</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">35</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">3</h6><h6 class="m-0 col-2 text-left">A.Rduch</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">27</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">5</h6><h6 class="m-0 col-2 text-left">T.Żbikowski</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">18</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">4</h6><h6 class="m-0 col-2 text-left">M.Blacha</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">6</h6><h6 class="m-0 col-2 text-left">S.Sikora</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">12</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">7</h6><h6 class="m-0 col-2 text-left">M.Baron</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">12</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">8</h6><h6 class="m-0 col-2 text-left">T.Kożdoń</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">9</h6><h6 class="m-0 col-2 text-left">K.Kawalec</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">10</h6><h6 class="m-0 col-2 text-left">M.Chotarski</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">11</h6><h6 class="m-0 col-2 text-left">A.Zawadka</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">9</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">12</h6><h6 class="m-0 col-2 text-left">M.Kasperski</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">12</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">13</h6><h6 class="m-0 col-2 text-left">K.Szturc</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">42</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">14</h6><h6 class="m-0 col-2 text-left">A.Podżorski</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">31</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">15</h6><h6 class="m-0 col-2 text-left">M.Watras</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">25</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">16</h6><h6 class="m-0 col-2 text-left">J.Kwiczala</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">22</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">17</h6><h6 class="m-0 col-2 text-left">D.Heczko</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">18</h6><h6 class="m-0 col-2 text-left">K.Kawalec</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">12</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">19</h6><h6 class="m-0 col-2 text-left">K.Ożga</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">12</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">20</h6><h6 class="m-0 col-2 text-left">T.Salomon</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">21</h6><h6 class="m-0 col-2 text-left">P.Piesko</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">22</h6><h6 class="m-0 col-2 text-left">F.Wajman</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">23</h6><h6 class="m-0 col-2 text-left">I.Chwist</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">24</h6><h6 class="m-0 col-2 text-left">T.Kobylański</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">25</h6><h6 class="m-0 col-2 text-left">P.Walek</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">26</h6><h6 class="m-0 col-2 text-left">P.Kolonko</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">14</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">27</h6><h6 class="m-0 col-2 text-left">R.Augustyn</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">28</h6><h6 class="m-0 col-2 text-left">R.Szpin</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">29</h6><h6 class="m-0 col-2 text-left">K.Holubek</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">30</h6><h6 class="m-0 col-2 text-left">T.Sanecznik</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">31</h6><h6 class="m-0 col-2 text-left">S.Wisełka</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">32</h6><h6 class="m-0 col-2 text-left">R.Dudek</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">33</h6><h6 class="m-0 col-2 text-left">S.Hus</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">21</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">34</h6><h6 class="m-0 col-2 text-left">G.Ira</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">21</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">35</h6><h6 class="m-0 col-2 text-left">M.Mitko</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">23</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">36</h6><h6 class="m-0 col-2 text-left">P.Kolonko</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">23</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">37</h6><h6 class="m-0 col-2 text-left">D.Holeksa</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">23</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">38</h6><h6 class="m-0 col-2 text-left">K.Kukła</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">23</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">39</h6><h6 class="m-0 col-2 text-left">M.Hajduk</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">23</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">40</h6><h6 class="m-0 col-2 text-left">A.Wypych</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">38</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">41</h6><h6 class="m-0 col-2 text-left">T.Plinta</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6></div><h6 class="m-0 col text-right">34</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">42</h6><h6 class="m-0 col-2 text-left">M.Grudka</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">21</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">43</h6><h6 class="m-0 col-2 text-left">D.Turoń</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">21</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">44</h6><h6 class="m-0 col-2 text-left">G.Ciombor</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">18</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">45</h6><h6 class="m-0 col-2 text-left">M.Pogorzelski</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">15</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">46</h6><h6 class="m-0 col-2 text-left">J.Stebel</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">47</h6><h6 class="m-0 col-2 text-left">A.Turoń</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">48</h6><h6 class="m-0 col-2 text-left">M.Radecki</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">49</h6><h6 class="m-0 col-2 text-left">M.Golec</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">50</h6><h6 class="m-0 col-2 text-left">M.Kawulok</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">51</h6><h6 class="m-0 col-2 text-left">A.Dobosz</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">12</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">52</h6><h6 class="m-0 col-2 text-left">P.Krysztowiak</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">53</h6><h6 class="m-0 col-2 text-left">D.Dembinny</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">14</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">54</h6><h6 class="m-0 col-2 text-left">K.Henkel</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">14</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">55</h6><h6 class="m-0 col-2 text-left">M.Świder</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">16</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">56</h6><h6 class="m-0 col-2 text-left">S.Gańcarczyk</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">16</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">57</h6><h6 class="m-0 col-2 text-left">P.Wiśniewski</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">16</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">58</h6><h6 class="m-0 col-2 text-left">D.Galeja</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">19</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">59</h6><h6 class="m-0 col-2 text-left">Ł.Szwarc</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">60</h6><h6 class="m-0 col-2 text-left">P.Ochnicki</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">21</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">61</h6><h6 class="m-0 col-2 text-left">A.Wilewski</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">21</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">62</h6><h6 class="m-0 col-2 text-left">M.Kozok</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">21</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">63</h6><h6 class="m-0 col-2 text-left">M.Darmstaendter</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">21</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">64</h6><h6 class="m-0 col-2 text-left">M.Kociołek</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">54</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">65</h6><h6 class="m-0 col-2 text-left">M.Gluza</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">34</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">66</h6><h6 class="m-0 col-2 text-left">T.Sanecznik</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">29</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">67</h6><h6 class="m-0 col-2 text-left">K.Żloch</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">16</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">68</h6><h6 class="m-0 col-2 text-left">M.Dudarewicz</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">15</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">69</h6><h6 class="m-0 col-2 text-left">M.Walaszek</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">70</h6><h6 class="m-0 col-2 text-left">M.Gromek</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">71</h6><h6 class="m-0 col-2 text-left">Z.Piela</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">72</h6><h6 class="m-0 col-2 text-left">J.Goździk</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">11</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">73</h6><h6 class="m-0 col-2 text-left">J.Piechoczek</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">74</h6><h6 class="m-0 col-2 text-left">Ł.Roik</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">75</h6><h6 class="m-0 col-2 text-left">W.Weyher</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">76</h6><h6 class="m-0 col-2 text-left">W.Pawiński</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">77</h6><h6 class="m-0 col-2 text-left">A.Chowaniak</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">78</h6><h6 class="m-0 col-2 text-left">P.Oślak</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">79</h6><h6 class="m-0 col-2 text-left">K.Henkel</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">80</h6><h6 class="m-0 col-2 text-left">K.Kwiczala</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">81</h6><h6 class="m-0 col-2 text-left">D.Michalski</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">82</h6><h6 class="m-0 col-2 text-left">M.Marczyk</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">39</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">83</h6><h6 class="m-0 col-2 text-left">P.Matusik</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">32</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">84</h6><h6 class="m-0 col-2 text-left">M.Biernat</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">26</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">85</h6><h6 class="m-0 col-2 text-left">A.Piechota</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">25</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">86</h6><h6 class="m-0 col-2 text-left">T.Kubica</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">18</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">87</h6><h6 class="m-0 col-2 text-left">S.Bugiel</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">17</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">88</h6><h6 class="m-0 col-2 text-left">M.Fila</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">12</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">89</h6><h6 class="m-0 col-2 text-left">J.Maciusiak</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">90</h6><h6 class="m-0 col-2 text-left">A.Skrędzelewski</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">9</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">91</h6><h6 class="m-0 col-2 text-left">R.Marzec</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">92</h6><h6 class="m-0 col-2 text-left">D.Wenglorz</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">93</h6><h6 class="m-0 col-2 text-left">W.Donocik</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">94</h6><h6 class="m-0 col-2 text-left">A.Chowaniak</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">95</h6><h6 class="m-0 col-2 text-left">T.Nowak</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">96</h6><h6 class="m-0 col-2 text-left">T.Danielczyk</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">97</h6><h6 class="m-0 col-2 text-left">M.Niemczyk</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">98</h6><h6 class="m-0 col-2 text-left">D.Skupień</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">99</h6><h6 class="m-0 col-2 text-left">S.Gorący</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">100</h6><h6 class="m-0 col-2 text-left">D.Wojciech</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">101</h6><h6 class="m-0 col-2 text-left">R.Duda</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">102</h6><h6 class="m-0 col-2 text-left">Ł.Kral</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">103</h6><h6 class="m-0 col-2 text-left">M.Sroka</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">104</h6><h6 class="m-0 col-2 text-left">K.Kogut</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">105</h6><h6 class="m-0 col-2 text-left">D.Uchyła</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">106</h6><h6 class="m-0 col-2 text-left">A.Kobielusz</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">107</h6><h6 class="m-0 col-2 text-left">S.Dawidow</h6><h6 class="m-0 col-2 text-left">cento</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">20</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">108</h6><h6 class="m-0 col-2 text-left">B.Podżorski</h6><h6 class="m-0 col-2 text-left">maluch</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">36</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">109</h6><h6 class="m-0 col-2 text-left">R.Telega</h6><h6 class="m-0 col-2 text-left">maluch</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">34</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">110</h6><h6 class="m-0 col-2 text-left">P.Filapek</h6><h6 class="m-0 col-2 text-left">maluch</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">32</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">111</h6><h6 class="m-0 col-2 text-left">D.Opioła</h6><h6 class="m-0 col-2 text-left">maluch</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">30</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">112</h6><h6 class="m-0 col-2 text-left">S.Goryczka</h6><h6 class="m-0 col-2 text-left">maluch</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">20</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">113</h6><h6 class="m-0 col-2 text-left">D.Gabzdyl</h6><h6 class="m-0 col-2 text-left">maluch</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">18</h6><h6 class="m-0 col text-center">6</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">114</h6><h6 class="m-0 col-2 text-left">M.Szpunar</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">54</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">115</h6><h6 class="m-0 col-2 text-left">P.Rączka</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">48</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">116</h6><h6 class="m-0 col-2 text-left">R.Górecki</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">27</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">117</h6><h6 class="m-0 col-2 text-left">B.Krzyżowski</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">24</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">118</h6><h6 class="m-0 col-2 text-left">M.Urbaczka</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">12</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">119</h6><h6 class="m-0 col-2 text-left">Ł.Krzyżowski</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">120</h6><h6 class="m-0 col-2 text-left">J.Sikora</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">121</h6><h6 class="m-0 col-2 text-left">Ł.Jarząbek</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">122</h6><h6 class="m-0 col-2 text-left">P.Kapturski</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">9</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">123</h6><h6 class="m-0 col-2 text-left">A.Chowaniak</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">124</h6><h6 class="m-0 col-2 text-left">P.Olbryś</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">125</h6><h6 class="m-0 col-2 text-left">D.Smółka</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection