@extends('layouts.app')

@section('content')
<div class="container-fluid py-3 overflow-auto">
    <div class="row justify-content-center">
        <div class="col-md-12">
            <div class="card border-dark fixed-width">
                <div class="card-header bg-yellow text-center">
                    <h3>Klasyfikacja Generalna: Rajdowy Puchar Śląska 2018</h3>
                </div>
                <div class="card-body">
                    <div class="row justify-content-between align-items-center flex-wrap">
                        <h6 class="m-0 col text-left">
                            LP
                        </h6>
                        <h6 class="m-0 col-2 text-left">
                            Imię i nazwisko
                        </h6>
                        <h6 class="m-0 col-2 text-left">
                            Klasa
                        </h6>
                        <div class="m-0 col-5 d-flex justify-content-start">
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 1</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 2</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 3</small>
                            </h6>
                            <h6 class="m-0 col-2 text-center">
                                <small>Runda 4</small>
                            </h6>
                        </div>
                        <h6 class="m-0 col text-right">
                            PKT
                        </h6>
                        <h6 class="m-0 col text-right">
                            Miejsce
                        </h6>
                        <hr class="col-12 p-0">
                    </div>
                    <div class="lista"> 
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">1</h6><h6 class="m-0 col-2 text-left">ŁUKASZ KOBIELA</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">22</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">2</h6><h6 class="m-0 col-2 text-left">MARIUSZ BLACHA</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">21</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">3</h6><h6 class="m-0 col-2 text-left">STANISŁAW LASSAK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">18</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">4</h6><h6 class="m-0 col-2 text-left">TOMASZ KOŻDOŃ</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">11</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">5</h6><h6 class="m-0 col-2 text-left">KAMIL HORNIK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">6</h6><h6 class="m-0 col-2 text-left">PIOTR TROSZOK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">7</h6><h6 class="m-0 col-2 text-left">TOMASZ JURKUN</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">8</h6><h6 class="m-0 col-2 text-left">ARTUR KOBIELA</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">9</h6><h6 class="m-0 col-2 text-left">MATEUSZ CHOTARSKI</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">10</h6><h6 class="m-0 col-2 text-left">JAN BALDWIN</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">11</h6><h6 class="m-0 col-2 text-left">TOMASZ ŻBIKOWSKI</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">12</h6><h6 class="m-0 col-2 text-left">PIOTR KACZMAREK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">13</h6><h6 class="m-0 col-2 text-left">MAREK SZPUNAR</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">14</h6><h6 class="m-0 col-2 text-left">ANDRZEJ RDUCH</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">15</h6><h6 class="m-0 col-2 text-left">AREK TYC</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">16</h6><h6 class="m-0 col-2 text-left">SŁAWOMIR SIKORA</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">16</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">17</h6><h6 class="m-0 col-2 text-left">PIOTR ŻBIKOWSKI</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">16</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">18</h6><h6 class="m-0 col-2 text-left">MIROSŁAW MACURA</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">19</h6><h6 class="m-0 col-2 text-left">MICHAŁ KOCIOŁEK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">20</h6><h6 class="m-0 col-2 text-left">MICHAŁ BARON</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">21</h6><h6 class="m-0 col-2 text-left">MARCIN OGRODNICZAK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">22</h6><h6 class="m-0 col-2 text-left">MAREK SZCZEŚNIAK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">23</h6><h6 class="m-0 col-2 text-left">ŁUKASZ PUDEŁEK</h6><h6 class="m-0 col-2 text-left">4</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">24</h6><h6 class="m-0 col-2 text-left">MACIEJ WATRAS</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">30</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">25</h6><h6 class="m-0 col-2 text-left">KRZYSZTOF SZTURC</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">30</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">26</h6><h6 class="m-0 col-2 text-left">KRYSTIAN KUROWSKI</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6></div><h6 class="m-0 col text-right">18</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">27</h6><h6 class="m-0 col-2 text-left">PRZEMYSŁAW MENDREK</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">28</h6><h6 class="m-0 col-2 text-left">SEBASTIAN DZIADOSZ</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">29</h6><h6 class="m-0 col-2 text-left">DAWID HOLEKSA</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">30</h6><h6 class="m-0 col-2 text-left">KACPER SIKORA</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">31</h6><h6 class="m-0 col-2 text-left">ARTUR PODŻORSKI</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">32</h6><h6 class="m-0 col-2 text-left">DANIEL KIEŁBIK</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">33</h6><h6 class="m-0 col-2 text-left">KRYSTIAN HOLUBEK</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">34</h6><h6 class="m-0 col-2 text-left">KAMIL KAWALEC</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">35</h6><h6 class="m-0 col-2 text-left">TOMASZ SALAMON</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">36</h6><h6 class="m-0 col-2 text-left">TOMASZ SANECZNIK</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">37</h6><h6 class="m-0 col-2 text-left">KRZYSZTOF DURAJ</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">13</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">38</h6><h6 class="m-0 col-2 text-left">TOMASZ KOBYLAŃSKI</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">39</h6><h6 class="m-0 col-2 text-left">PAWEŁ KOLONKO</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">40</h6><h6 class="m-0 col-2 text-left">SZYMON ROMANIUK</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">41</h6><h6 class="m-0 col-2 text-left">MATEUSZ DARMSTAEDTER</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">42</h6><h6 class="m-0 col-2 text-left">SZYMON WISEŁKA</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">43</h6><h6 class="m-0 col-2 text-left">JERZY PODŻORSKI</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">44</h6><h6 class="m-0 col-2 text-left">KRYSTIAN OŻGA</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">45</h6><h6 class="m-0 col-2 text-left">IZAAK CHWIST</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">46</h6><h6 class="m-0 col-2 text-left">MICHAŁ MITKO</h6><h6 class="m-0 col-2 text-left">3</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">17</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">47</h6><h6 class="m-0 col-2 text-left">MARIUSZ CIEŚLAR</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">25</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">48</h6><h6 class="m-0 col-2 text-left">JANUSZ STEBEL</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">24</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">49</h6><h6 class="m-0 col-2 text-left">TOMASZ PLINTA</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">22</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">50</h6><h6 class="m-0 col-2 text-left">SZYMON GAŃCZARCZYK</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">15</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">51</h6><h6 class="m-0 col-2 text-left">MARCIN ŚWIDER</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">52</h6><h6 class="m-0 col-2 text-left">DANIEL DEMBINNY</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">53</h6><h6 class="m-0 col-2 text-left">TOMASZ ANDRZEJEWSKI</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">54</h6><h6 class="m-0 col-2 text-left">ADAM WYPYCH</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">55</h6><h6 class="m-0 col-2 text-left">ZBIGNIEW CIEŚLAR</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">56</h6><h6 class="m-0 col-2 text-left">ARKADIUSZ CZEKAN</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">57</h6><h6 class="m-0 col-2 text-left">PIOTR OCHNICKI</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">58</h6><h6 class="m-0 col-2 text-left">MARIUSZ GRUDKA</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">59</h6><h6 class="m-0 col-2 text-left">RAFAŁ KAMIŃSKI</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">60</h6><h6 class="m-0 col-2 text-left">JERZY NIEMIEC</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">14</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">61</h6><h6 class="m-0 col-2 text-left">PATRYK SIĄKAŁA</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">14</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">62</h6><h6 class="m-0 col-2 text-left">SZYMON OJCZYK</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">16</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">63</h6><h6 class="m-0 col-2 text-left">PIOTR WIŚNIEWSKI</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">17</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">64</h6><h6 class="m-0 col-2 text-left">ANDRZEJ DOBOSZ</h6><h6 class="m-0 col-2 text-left">2</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">18</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">65</h6><h6 class="m-0 col-2 text-left">TOMASZ SANECZNIK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">36</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">66</h6><h6 class="m-0 col-2 text-left">MARCIN GLUZA</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">26</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">67</h6><h6 class="m-0 col-2 text-left">ŁUKASZ ROIK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">15</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">68</h6><h6 class="m-0 col-2 text-left">SEBASTIAN HUS</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">69</h6><h6 class="m-0 col-2 text-left">MACIEJ WALASZEK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">11</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">70</h6><h6 class="m-0 col-2 text-left">KRZYSZTOF ZLOCH</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">10</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">71</h6><h6 class="m-0 col-2 text-left">MARCIN DUDAREWICZ</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">72</h6><h6 class="m-0 col-2 text-left">GRZEGORZ BIENIEK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">73</h6><h6 class="m-0 col-2 text-left">JAKUB PIECHOCZEK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">74</h6><h6 class="m-0 col-2 text-left">JACEK GOŹDZIK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">75</h6><h6 class="m-0 col-2 text-left">PIOTR FILAPEK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">76</h6><h6 class="m-0 col-2 text-left">BARBARA PIETRZYK</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">77</h6><h6 class="m-0 col-2 text-left">PAWEŁ PRUSINOWSKI</h6><h6 class="m-0 col-2 text-left">1</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">13</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">78</h6><h6 class="m-0 col-2 text-left">MARCIN STEFANIK</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">31</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">79</h6><h6 class="m-0 col-2 text-left">MATUFA </h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">28</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">80</h6><h6 class="m-0 col-2 text-left">SEBASTIAN BUGIEL</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">22</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">81</h6><h6 class="m-0 col-2 text-left">WOJCIECH DONOCIK</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">13</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">82</h6><h6 class="m-0 col-2 text-left">DAMIAN SKUPIEŃ</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">11</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">83</h6><h6 class="m-0 col-2 text-left">WOJCIECH NAJGRODZKI</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">9</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">84</h6><h6 class="m-0 col-2 text-left">KRZYSZTOF HENKEl</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">85</h6><h6 class="m-0 col-2 text-left">DAMIAN BONCELA</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">86</h6><h6 class="m-0 col-2 text-left">DOMINIK WENGLORZ</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">9</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">87</h6><h6 class="m-0 col-2 text-left">ARTUR SKRĘDZELEWSKI</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">88</h6><h6 class="m-0 col-2 text-left">SZYMON DAWIDÓW</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">89</h6><h6 class="m-0 col-2 text-left">DAMIAN UCHYŁA</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">12</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">90</h6><h6 class="m-0 col-2 text-left">ŁUKASZ KRAL</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">2</h6><h6 class="m-0 col text-center">12</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">91</h6><h6 class="m-0 col-2 text-left">ANDRZEJ LESKIW</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">1</h6><h6 class="m-0 col text-center">14</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">92</h6><h6 class="m-0 col-2 text-left">RADOSŁAW BRACHACZEK</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">93</h6><h6 class="m-0 col-2 text-left">PAWEŁ KOZIOŁ</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">94</h6><h6 class="m-0 col-2 text-left">MATEUSZ MARCZYK</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">95</h6><h6 class="m-0 col-2 text-left">RAFAŁ MARZEC</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">96</h6><h6 class="m-0 col-2 text-left">MACIEJ SROKA</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">97</h6><h6 class="m-0 col-2 text-left">ŁUKASZ ZIEJA</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">98</h6><h6 class="m-0 col-2 text-left">MARCIN IDZI</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">99</h6><h6 class="m-0 col-2 text-left">SŁAWOMIR GORĄCY</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">100</h6><h6 class="m-0 col-2 text-left">RADEK DUDA</h6><h6 class="m-0 col-2 text-left">CENTO</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>0</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">15</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">101</h6><h6 class="m-0 col-2 text-left">PAWEŁ RĄCZKA</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">38</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">102</h6><h6 class="m-0 col-2 text-left">JAKUB SIKORA</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">28</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">103</h6><h6 class="m-0 col-2 text-left">ROBERT GÓRECKI</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6></div><h6 class="m-0 col text-right">23</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">104</h6><h6 class="m-0 col-2 text-left">MATEUSZ URBACZKA</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">17</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">105</h6><h6 class="m-0 col-2 text-left">BARTOSZ KRZYŻOWSKI</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">11</h6><h6 class="m-0 col text-center">5</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">106</h6><h6 class="m-0 col-2 text-left">PIOTR KAPTURSKI</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>2</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">8</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">107</h6><h6 class="m-0 col-2 text-left">SEBASTIAN WOLNY</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6></div><h6 class="m-0 col text-right">7</h6><h6 class="m-0 col text-center">7</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">108</h6><h6 class="m-0 col-2 text-left">DANIEL SIKORA</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">109</h6><h6 class="m-0 col-2 text-left">WOJCIECH KASZOWSKI</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">6</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">110</h6><h6 class="m-0 col-2 text-left">ADAM CHOWANIAK</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>1</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">10</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">111</h6><h6 class="m-0 col-2 text-left">ŁUKASZ JARZĄBEK</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>3</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">3</h6><h6 class="m-0 col text-center">11</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">112</h6><h6 class="m-0 col-2 text-left">KAMIL MICHTA</h6><h6 class="m-0 col-2 text-left">RWD</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">12</h6></div>
                        <hr>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">113</h6><h6 class="m-0 col-2 text-left">RAFAŁ TELEGA</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6></div><h6 class="m-0 col text-right">34</h6><h6 class="m-0 col text-center">1</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">114</h6><h6 class="m-0 col-2 text-left">DANIEL OPIOŁA</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>10</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>4</small></h6></div><h6 class="m-0 col text-right">24</h6><h6 class="m-0 col text-center">2</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">115</h6><h6 class="m-0 col-2 text-left">DAMIAN GABZDYL</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6></div><h6 class="m-0 col text-right">19</h6><h6 class="m-0 col text-center">3</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">116</h6><h6 class="m-0 col-2 text-left">BARTŁOMIEJ PODŻORSKI</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">117</h6><h6 class="m-0 col-2 text-left">BARTOSZ NIEWIADOMSKI</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>8</small></h6><h6 class="m-0 col-2 text-center"><small>6</small></h6></div><h6 class="m-0 col text-right">14</h6><h6 class="m-0 col text-center">4</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">118</h6><h6 class="m-0 col-2 text-left">JAKUB ADAMUS</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">119</h6><h6 class="m-0 col-2 text-left">MATEUSZ DUDA</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>5</small></h6></div><h6 class="m-0 col text-right">5</h6><h6 class="m-0 col text-center">6</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">120</h6><h6 class="m-0 col-2 text-left">PIOTR FILAPEK</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>4</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">4</h6><h6 class="m-0 col text-center">8</h6></div>
                        <div class="row justify-content-between align-items-center flex-wrap py-2"><h6 class="m-0 col">121</h6><h6 class="m-0 col-2 text-left">TOMASZ SOTOŁA</h6><h6 class="m-0 col-2 text-left">MALUCH</h6><div class="m-0 col-5 d-flex justify-content-start"><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6><h6 class="m-0 col-2 text-center"><small>N</small></h6></div><h6 class="m-0 col text-right">0</h6><h6 class="m-0 col text-center">9</h6></div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection